# Generated by Django 4.1.7 on 2023-03-13 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Video', '0002_video_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='category',
            field=models.CharField(choices=[('1', 'Quran'), ('2', 'Hadith'), ('3', 'Fiqh'), ('4', 'Heart Softener'), ('5', 'Biography'), ('6', 'Debate'), ('7', 'Dawah')], default='Others', max_length=21),
        ),
    ]
