# Generated by Django 4.1.7 on 2023-03-14 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Video', '0003_alter_video_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='video',
            name='category',
            field=models.CharField(choices=[('1', 'Quran'), ('2', 'Hadith'), ('3', 'Fiqh'), ('4', 'Heart Softener'), ('5', 'Biography'), ('6', 'Debate'), ('7', 'Dawah')], default='Islamic', max_length=255),
        ),
    ]
